services:
  - type: web
    name: voicemood-api
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: WHISPER_MODEL_SIZE
        value: base.en
      - key: WHISPER_DEVICE
        value: cpu
      - key: WHISPER_COMPUTE_TYPE
        value: int8
      - key: WHISPER_LANGUAGE
        value: en
      - key: WHISPER_BEAM_SIZE
        value: "1"
      - key: ACOUSTIC_SAMPLE_RATE
        value: "16000"
